### ISSUE TITLE
BUG: subdataset filtering not working

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#10]
With the current site in production, I get the following when starting to type in the search field:

```
vue.js:634 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'toLowerCase')"

found in

---> <Anonymous>
       <Root>
warn @ vue.js:634
logError @ vue.js:1902
globalHandleError @ vue.js:1897
handleError @ vue.js:1857
Vue._render @ vue.js:3574
updateComponent @ vue.js:4082
get @ vue.js:4494
run @ vue.js:4569
flushSchedulerQueue @ vue.js:4327
(anonymous) @ vue.js:1998
flushCallbacks @ vue.js:1924
Promise.then (async)
timerFunc @ vue.js:1951
nextTick @ vue.js:2008
queueWatcher @ vue.js:4419
update @ vue.js:4559
notify @ vue.js:745
reactiveSetter @ vue.js:1070
proxySetter @ vue.js:4643
onInput @ bootstrap-vue.2.21.2.min.js:10
invokeWithErrorHandling @ vue.js:1872
invoker @ vue.js:2197
original._wrapper @ vue.js:7591
vue.js:1906 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at app_component_dataset.js:217:28
    at Array.some (<anonymous>)
    at app_component_dataset.js:215:27
    at Array.filter (<anonymous>)
    at VueComponent.filteredSubdatasets (app_component_dataset.js:208:36)
    at Watcher.get (vue.js:4494:27)
    at Watcher.evaluate (vue.js:4596:23)
    at VueComponent.computedGetter [as filteredSubdatasets] (vue.js:4847:19)
    at VueComponent.tagFilteredSubdatasets (app_component_dataset.js:223:32)
    at Watcher.get (vue.js:4494:27)
```

**Comment by jsheunis** [comment]
This is a result of a couple of issues:
- the catalog schema does not have required fields for authors, it should
- the metadata in sfb catalog includes mostly `givenName` and `familyName`
- the catalog JS code filters in `name` (a concatenation of the two above)

I propose to fix this for the sfb catalog by adding the name field to all author dictionaries in the metadata, and then do a permanent fix in datalad-catalog by updating both the schema and the filtering code.

**Comment by mslw** [comment]
Yikes!

For context:
- We are using CFF for describing project datasets
- In CFF, authors is an Array of [definitions.person](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsperson) and/or [definitions.entity](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsentity) objects. 
- Entity has name; Person gas given-names, family-names, name-particle, & name-suffix; but not name (I keep to that when translating)
- I wasn't sure how to interpret the catalog schema (if name is a concatenation of other fields it seemed redundant), and displaying authors worked with givenName & familyName

I think it makes sense to fix it by adding a postprocessing step for the metadata in the catalog first, and leave the "proper" fix in the catalog for later. But I won't prioritize it ATM.

Do you think updating filtering code in the SFB catalog would be an easy alternative?

**Comment by jsheunis** [comment]
Thanks for the info. Currently trying to see if i can get the filtering to work. If not, I'll update the data.

**Comment by mslw** [comment]
I can confirm that this bug still occurs.

Looking at linked issues / PRs and related code, a workaround had been introduced in this repo, but there was no fix in datalad-catalog (the corresponding datalad-catalog issue is open). Consequently, the workaround has been overwritten when JS app component and HTML template used by this catalog got updated to match current catalog main.

As stated above, the filtering fails when a (dataset) author has no "name" property (but uses "givenName" and "familyName" instead). This is different for different metadata sources (e.g. metadata from CFF has "givenName" & "familyName" while metadata from tabby has "name"). Therefore problems with filtering can be seen e.g. in A02 but not Z02 at the moment.

The suggestion to always include "name" would necessitate updating metadata translators and repeating metadata extraction for all affected datasets.

I would currently favor a fix to catalog, as its schema (theoretically) allows not having "name". It looks to me though that the workaround from fbf3da1 is probably not a full fix as it might create an opposite problem ("name" present but "familyName" not).

**Comment by jsheunis** [comment]
ouch @ reintroducing the error.

I agree, a fix in catalog is the way to do this. I work on this and update https://github.com/datalad/datalad-catalog/issues/291.

I propose a fix that merges the state prior to fbf3da12b57b85ad2337aea5628e1a2ebd6b8269 with the change that is introduced by the same commit.

**Comment by mslw** [comment]
> I propose a fix that merges the state prior to https://github.com/psychoinformatics-de/sfb1451-projects-catalog/commit/fbf3da12b57b85ad2337aea5628e1a2ebd6b8269 with the change that is introduced by the same commit.

But then it would ignore "name" completely, wouldn't it? As it stands, dataset metadata can use either representation, depending on what process generated it.

**Comment by jsheunis** [comment]
Sorry I should have been clearer. I will update the code to filter on any of the options (`name`, `givenName`, `familyName`) if they exist in a given record.
