### ISSUE TITLE
BUG: filter fields disappearing when filtering returns zero results

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#11]
the field should only be invisible if there aren't any subdatasets to begin with.

**Comment by jsheunis** [comment]
See 45e0013e3f604e06f7fa69f0be3a6157d85e1b3f

**Comment by mslw** [comment]
Given that:
- a tracking issue in the catalog repo is closed
- JS app component and HTML template used by this catalog have been updated to match current catalog main
- I can not replicate the bug

I think the issue can be considered resolved.
