### ISSUE TITLE
Add "request data access" contact to datasets

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#19]
Need to update the metadata of each (?) project dataset to include either an `access_request_contact` (the likely option) or an `access_request_url`.

This is what the schemas look like, with examples.

**`access_request_contact`:**
```
"access_request_contact" : {
      "description": "The contact details of the person/office from which to request access to the dataset content",
      "title": "Access Request Contact",
      "type": "object",
      "properties": {
        "givenName": {
          "description": "The author's given name, such as 'John'",
          "title": "Given name",
          "type": "string"
        },
        "familyName": {
          "description": "The author's last/family name, such as 'Doe'",
          "title": "Family name",
          "type": "string"
        },
        "name": {
          "description": "A concatenation of the honorificSuffix, givenName and familyName properties, such as 'Dr. John Doe'",
          "title": "Name",
          "type": "string"
        },
        "email": {
          "description": "Email address of the author, such as johndoe@example.com",
          "title": "Email",
          "type": "string",
          "format": "email"
        },
        "honorificSuffix": {
          "description": "Title of the author, such as 'Dr.'",
          "title": "Honorific suffix",
          "type": "string"
        },
        "identifiers": {
          "description": "Identifiers for the person",
          "title": "Identifiers",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "description": "Type of identifier, such as 'ORCID'",
                "title": "Type",
                "type": "string"
              },
              "identifier": {
                "description": "The actual identifier, such as the ORCID ID '0000-1212-5566'",
                "title": "Identifier",
                "type": "string"
              }
            }
          }
        }
      },
      "required": ["givenName", "familyName", "email"]
    },
```

example:

```
metadata: {
   ...
   "access_request_contact": {
      "givenName": "John",
      "familyName": "Doe",
      "email": "johndoe@abcd.org",
   }
   ...
}
```

**`access_request_url`:**
```
    "access_request_url": { 
      "type": "string",
      "description": "The url of the online location from which to request access to the dataset content",
      "title": "Access Request URL",
      "format": "uri"
    },
```

example:

```
metadata: {
   ...
   "access_request_url": "https://abcd.org"
   ...
}
```

**Comment by jsheunis** [comment]
Would be simplified a lot if we only have to add one contact per project dataset with data, which assumes:
- projects without data do not need contact persons (other than names of dataset authors)
- all of a project's subdatasets (which may or may not contain more data) have the same contact person

**Comment by mslw** [comment]
Since I am pushing the CFF format for most of our annotations, CFF has [contact](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#contact) that would map nicely onto `access_request_contact`.

The [translator](https://github.com/mslw/datalad-wackyextra/blob/main/datalad_wackyextra/translators/cff.py) I am using for CFF does not currently "take" that field.

We could set the expectation / populate that field for project superdatasets, and then re-extract the project metadata, assuring the contact info would be present for any future revisions.

If we are going the way of catalog patching, it would be best to add this as an option to `code/inject_metadata.py`.

**Comment by mslw** [comment]
- The catalog now has access request contact button https://github.com/datalad/datalad-catalog/pull/235
- We are using tabby to populate these fields, by taking the first "data controller" that was declared
- We additionally report all data controllers in the SFB1451 tab
- Our tooling does not support using CFF for contact info, but we also don't have real examples of usage of the field

Overall, I would consider it closed.
