### ISSUE TITLE
Add subdataset dataset DOI/url to subdatasets view

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#22]
As displayed currently on the "Publications" view.

**Comment by jsheunis** [comment]
IIRC only the catalog's javascript code needs to be updated for this change, i.e. nothing would be needed re catalog entry generation/update.

**Comment by jsheunis** [comment]
Ok, it was both JS and html, but not a major change... Here's a sample:

<img width="1321" alt="Screenshot 2023-10-06 at 15 36 12" src="https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/10141237/fba0fbe7-e204-4f05-8d4b-987fc4c9340f">

**Comment by jsheunis** [comment]
One thing to know about the decision to go with https://shields.io/ is that the current link references the online badge images, i.e. connectivity is needed.

**Comment by mslw** [comment]
Personally i'm OK with connectivity, can't remember ever viewing the catalog offline.

Also personally, I think it a badge feels a bit heavy, visually. Curious to get other opinions.

**Comment by jsheunis** [comment]
Here's an example with URL also shown. the `url` property on a dataset is an array, since there could be multiple URLs. At the moment I'm arbitrarily displaying the last element in the array. Also, I'm not displaying it in the same way as the two-part `DOI | some/doi`, because a dataset URL might be quite long, and that is visually not great.

<img width="1341" alt="Screenshot 2023-10-06 at 15 56 07" src="https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/10141237/7a49d7c5-9e9d-47c4-8fff-7f2c9f8b14fc">

**Comment by mslw** [comment]
Going back to this issue and taking a fresh look, I think I'm leaning (slightly) towards having the DOI badge and no URL badge.

At first I thought that showing the DOI like all other fields are shown (version, modified) would make most sense, and a badge looks a bit off compared to all other elements. But now I think that a doi badge looks like a "distinction" awarded to the dataset, which is probably a positive thing to do in recognition of good practice. Having a URL is less of a distinction, and the badge (short or long) looks more off than the doi badge.

**Comment by mslw** [comment]
Note: one way to display badges without relying on external services could be to have two `div`s (one containing word "DOI" and the other containing doi itself) styled with `color` and `border-*-radius`, possibly in another `div` - GIN does that.

And BTW, the JS code powering shields.io, [badge-maker](https://github.com/badges/shields/tree/master/badge-maker) is CC0. [Badgen](https://github.com/badgen/badgen), the library powering badgen.net is ISC licensed, and should be lighter.
