### ISSUE TITLE
Move repo to sfb1451 org?

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#26]
See https://github.com/mslw/tabby-utils/issues/5

**Comment by mslw** [comment]
That would be logical, but I'd prefer to keep it here until we're ready for a more official deployment - the current GitHub pages link has been communicated in a couple of places and keeping things here would be the best way to (not) manage redirections.

**Comment by mih** [comment]
The SFB1451 data policy was adopted. This enables a more official deployment.

**Comment by mslw** [comment]
The official deployment has been using the https://data.sfb1451.de address for a while now.

The repository transfer was done just now.
