### ISSUE TITLE
Mangle GIN URLs a bit more

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#3]
With my updated workflow I got `ssh://git@gin.g-node.org/user/repo.git` as `distribution.url` (origin) from metalad_core. This translated into a non-functional "View on GIN" button, as it kept the SSH URL. This can be solved with a following patch:

``` diff
diff --git a/docs/assets/app_component_dataset.js b/docs/assets/app_component_dataset.js
index 1e991f0..d19dd04 100644
--- a/docs/assets/app_component_dataset.js
+++ b/docs/assets/app_component_dataset.js
@@ -143,6 +143,7 @@ const datasetView = () =>
                     disp_dataset.is_gin = true;
                     disp_dataset.url = dataset.url[i];
                     disp_dataset.url = disp_dataset.url.replace('git@gin.g-node.org:', 'https://gin.g-node.org');
+                    disp_dataset.url = disp_dataset.url.replace('ssh://git@gin.g-node.org', 'https://gin.g-node.org');
                   }
                 }
                 if (!disp_dataset.url) {
```

Not sure if that's a change in the dataset or in metalad_core (using 0.4.16) - catalog already mangles the paths (as seen above) and I'm sure it worked before.

**Comment by jsheunis** [comment]
Could be that it worked previously because of a patch that was applied in a specific catalog rendering, and not in `datalad-catalog` itself. I will fix this.

**Comment by mslw** [comment]
I think these are now properly mangled :-)

(and I also realized the importance for fixing them "at the source", for those who come through the superdataset and not through the catalog)
