### ISSUE TITLE
How to represent submodules which aren't DataLad datasets?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#30]
We should be able to show catalog pages for datasets that are not DataLad datasets (e.g. GitHub repos used for code and/or data). Practical examples include:

- https://github.com/Aswendt-Lab/AIDAqc (C01, code-only project)
- https://gin.g-node.org/Aswendt_Lab/2023_Stokowska_Periinfarct (C01, non-DataLad GIN project)
- https://github.com/nawrotlab/SNN_GeNN_Nest (A06)

The catalog would need a dataset ID to show those. I might be wrong, but from my memory metalad-based extractors (such as `metalad_core`) would also not report anything on such submodules.

Possible solutions:

1. "Mint" a UUID v5 identifier in a similar way that we do for tabby but with different inputs, e.g. `uuid.uuid5(uuid.uuid5(uuid.NAMESPACE_DNS, 'github.com'), "org_name/repo_name"))` and use that as dataset id for generating catalog metadata in a custom way (e.g. based on `iter-gitworktree` for file listings)
2. Like (2) but Use a non-UUID string as the dataset id
3. Fork the project into sfb1451 org, run `datalad create --force` to generate `.datalad` file with UUID; use and report the fork for all catalog-related purposes
4. Make a PR to the project proposing changes described in (3), extract metadata only if accepted

TBH, I like (1) the most, even though I'm not 100% sure on all the details of metadata generation in practice.

Looking for feedback, mostly from @mih and @jsheunis

**Comment by jsheunis** [comment]
> The catalog would need a dataset ID to show those. I might be wrong, but from my memory metalad-based extractors (such as metalad_core) would also not report anything on such submodules.

IIRC `metalad_core` would list such a submodule as part of the `hasPart` array in the extracted metadata, but the specific submodule would not have a `datalad_id`.

I also like (1). We would have to standardise the approach somehow though.

**Comment by mslw** [comment]
Another option that crossed my mind: generate a tabby record from such a dataset. Then, dataset name would be entered by hand (if a GitHub repo: probably repo name verbatim), and UUID would be minted using the same convention as for other tabby datasets:

``` python
        uuid.uuid5(
            uuid.uuid5(uuid.NAMESPACE_DNS, "datalad.org"),
            f"sfb1451.{project}.{name}"
    )
```

The tabby metadata could be hand-edited by us, and the files table could be easily generated...

**Comment by mslw** [comment]
Alternatively, I would propose to generate UUID based on parts of the origin URL:
- namespace: netloc or its equivalent, e.g. `github.com` or `gin.g-node.org`
- url: path, e.g. `mslw/my-dataset`

This would (roughly) be the implementation:

``` python
from pathlib import Path
from urllib.parse import urlparse
import uuid
from datalad_next.datasets import Dataset

ds = Dataset(args.dataset)

origin = ds.siblings(
    action="query",
    name="origin",
    result_renderer="disabled",
    return_type="item-or-list",
)

url = origin["url"]
if url.endswith(".git"):
    url = url[:-4]

if url.startswith("http"):
    # e.g. https://github.com/foo/bar
    parsed_url = urlparse(url)
    netloc = parsed_url.netloc
    path = parsed_url.path
else:
    # e.g. git@github.com:foo/bar
    user_host, _, path = url.partition(":")
    user, _, netloc = user_host.rpartition("@")

uuid = uuid.uuid5(uuid.uuid5(uuid.NAMESPACE_DNS, netloc), path.lstrip("/"))

```

**Comment by mslw** [comment]
So far I was able to either work with authors to convert a dataset to a DataLad dataset, or to quickly generate a tabby record with file listing and all required descriptions.

I think the issue can be closed, as we discussed the options and there is no action to be taken.
