### ISSUE TITLE
Sizing issue with dataset buttons

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#31]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/fb28b9ae-6101-4300-b2f0-aa8dc796711e)

Minor, but still worth fixing.

**Comment by jsheunis** [comment]
Do you maybe have more information on the circumstances under which this occurs? Size of screen, type of browser? Would be good to see if I can reproduce this. It looks to me like the size of the datalad and binder icons need to become better at scaling.

**Comment by jsheunis** [comment]
A fix for this is now in `datalad-catalog` main.
