### ISSUE TITLE
No possibility navigate to a superdataset

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#34]
On, e.g., this dataset page: https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/a808f9e1-d638-4771-ae4c-ff21da29151a/272e2844cd7c58dda8dfe288e7831ad2fa9c34b6

There is no possibility to navigate to the respective superdataset.

This is a consequence of the fact that any given dataset version (that such a page corresponds to) can have any number of superdatasets (context).

However, this conceptual fact is not immediately obvious to a reader, hence the expectation to be able to "go to the outer context" is a valid one.

For the use case of having navigated to this page via a superdataset, the browsers "back button" achieves a solution. It would be worth considering to represent that with a (duplicate) on-page button/link.

For the use case of this page being a "landing page" that was itself the entrypoint for a catalog browsing, it would be useful to

- be able to query for *any* use of this *particular dataset version* as a subdataset (and get a list of links)
- be able to query for *any* use of this *dataset (regardless of the particular version* as a subdataset (and get a list of links)

**Comment by mih** [comment]
Another idea: The catalog URL could support a dedicated context identifier. IOW we make the "back target" explicit. If the URL contain this information, some kind of "back link" is shown, if not, then not.

This would allow users to provide contextualized catalog links, ie. point to a specific dataset version, in the context of another (super)dataset.

**Comment by jsheunis** [comment]
https://github.com/psychoinformatics-de/sfb1451-projects-catalog/pull/50 brings in changes from `datalad-catalog` that adds an explicit back-navigation button.

However this does not address the wider context of the issue described here. For the functionality of searching a full catalog for relationships, I have opened: https://github.com/datalad/datalad-catalog/issues/360

Regarding:

> Another idea: The catalog URL could support a dedicated context identifier. IOW we make the "back target" explicit. If the URL contain this information, some kind of "back link" is shown, if not, then not.
> This would allow users to provide contextualized catalog links, ie. point to a specific dataset version, in the context of another (super)dataset.

I like this idea. Created a related issue: https://github.com/datalad/datalad-catalog/issues/382

**Comment by mih** [comment]
This is implemented in the current draft:

![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/f2773337-fb36-4efd-b386-e3cfa104448b)
