### ISSUE TITLE
Twitter is dead

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#38]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/56cc6c29-a4ea-4104-9597-c8e614bef722)

Maybe say X (Twitter) -- or something along these lines.

**Comment by jsheunis** [comment]
PR to be submitted by Friedrich Nietzsche

**Comment by jsheunis** [comment]
Fixed in `datalad-catalog` main
