### ISSUE TITLE
Misleading click-action-promise in content tab

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#39]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/2aa1a7d3-fe37-440c-9986-44070ee39a79)

Each name in the content listing shown above is "clickable" (as indicated by a change in the cursor on hover). But only for directories clicking results in any action (expand directory subtree).

Downloadable files have a small "cloud" symbol in their row on the right.

It would make sense to me to duplicate the hyperlink for downloading a file with the actual file name as the anchor. This would give some files an actual click actions. Users may expect filenames to functions as download links from other content listings (e.g., standard apache functionality).

The cloud symbol could stay as it, or be demoted to an indicator symbol only.

**Comment by jsheunis** [comment]
Makes sense to me too 👍
