### ISSUE TITLE
Publications are duplicated

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#4]
Since we added Crossref metadata based on the list taken from the sfb [publications page](https://www.crc1451.uni-koeln.de/index.php/intern-2/), projects who provided their own lists in publication datasets have their papers duplicated (see e.g. C01 or INF in the [online catalog](https://psychoinformatics-de.github.io/sfb1451-projects-catalog)). Should I:

- deduplicate in the datasets (by reverting changes done by myself)
- set priorities in the catalog (nbib > ris > crossref; the first two were provided by users, the latter by me)
- leave deduplications to users (once we share the datasets back; all additions were done in sfb-retreat-2023 branch)?

**Comment by mih** [comment]
Two ways that I can see:

Have an identifier that serves as a key used for deduplicating (e.g. the DOI) across all sources.

Add a field to the autogenerated metadata that keeps, but disables an entry. This would enable rerunning the queries and retaining the result of prior manual curation efforts.

In general, I doubt that there can be a reliable automatic procedure with not manual curation involved. So enabling manual curation with a lasting impact should be the focus of any solution. IMHO.

**Comment by mslw** [comment]
Using DOI as an identifier remains a good idea (note: due to different metadata sources and publication types not all publications have a doi), but the publications were de-duplicated manually in the project-datasets.
