### ISSUE TITLE
(tabby) metadata is "linked-data"

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#41]
Looking at the `SFB1451` tabs, information is unconditionally rendered as text.

![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/400eec4c-f3ad-4939-a2ad-4afb8a3d0c44)

I think it would be better to assume that any metadata is "linked data", i.e. has some "definition URL" associated with any key and/or value.

In the example above, practically any word is either a hyperlink text, or (part of) the hyperlink target. This included the "property" labels.

That being said, the catalog should not necessarily be constrained to linked (meta)data. However, it should look particularly splendid for high-quality metadata.

**Comment by jsheunis** [comment]
Currently playing around with this. The idea is to either display the properties as links, which then point to the definitions. Or show definition URLs upon hover over the relevant element.

What's your first impression of hover tooltips?


https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/10141237/99c64fcd-fa9a-421e-8ac0-fdb7df1b490e

I tried links, but if some fields have definitions and others not, the sporadic rendering of links and normal text makes for a messy UX, IMHO.

Could also consider placing a small `i` icon next to all fields with definitions to make it clearer that there is indeed a definition being pointed to.

**Comment by jsheunis** [comment]
The above is the result of some local work along the lines of https://github.com/datalad/datalad-catalog/issues/341#issuecomment-1730302872

**Comment by mih** [comment]
Linking #46 here for more conceptual thoughts on semantic metadata in the catalog.

re demo above: I have no definitive opinion. The demo is concerned with definitions of property labels (relationships). This are typically IRI (not URLs), so this kind of annotation is appropriate (and may eventually be complemented with a some on-demand definition look-up, maybe via OLS).

The values/objects shown on the right a different story. The email+name person record is nothing but a `mailto` link in my book. And the homepage URL, is an actual URL that should be a link.

We might need to have a conversation on how to extend the tabby conventions for the SFB catalog to make the datatype more explicit.

**Comment by jsheunis** [comment]
See existing definitions in the SFB1451-specific convention:
https://github.com/sfb1451/tabby-utils/blob/14e660d4ae0b7016bc2b6eb8febbc0ffb2d4e932/load_tabby.py#L306


```python
cat_context = {
    "schema": "https://schema.org/",
    "bibo": "https://purl.org/ontology/bibo/",
    "dcterms": "https://purl.org/dc/terms/",
    "nfo": "https://www.semanticdesktop.org/ontologies/2007/03/22/nfo/#",
    "obo": "https://purl.obolibrary.org/obo/",
    "name": "schema:name",
    "title": "schema:title",
    "description": "schema:description",
    "doi": "bibo:doi",
    "version": "schema:version",
    "license": "schema:license",
    "description": "schema:description",
    "authors": "schema:author",
    "orcid": "obo:IAO_0000708",
    "email": "schema:email",
    "keywords": "schema:keywords",
    "funding": {
        "@id": "schema:funding",
        "@context": {
            "name": "schema:funder",
            "identifier": "schema:identifier",
        },
    },
    "publications": {
        "@id": "schema:citation",
        "@context": {
            "doi": "schema:identifier",
            "datePublished": "schema:datePublished",
            "citation": "schema:citation",
        },
    },
    "fileList": {
        "@id": "dcterms:hasPart",
        "@context": {
            "contentbytesize": "nfo:fileSize",
            "md5sum": "obo:NCIT_C171276",
            "path": "schema:name",
            "url": "schema:contentUrl",
        },
    },
    "address": "schema:PostalAddress",
    "sfbHomepage": "schema:mainEntityOfPage",
    "sfbDataController": "https://w3id.org/dpv#hasDataController",
    "sfbUsedFor": {
        "@id": "http://www.w3.org/ns/prov#hadUsage",
        "@context": {
            "url": "schema:url",
        },
    },
}

# no defined context for:
# crc-project, sample[organism], sample[organism-part]
```

Possible definitions:
- crc-project: https://schema.org/ResearchProject
- sample[organism]: 
   - http://purl.obolibrary.org/obo/UBERON_0000468
   - http://rs.tdwg.org/dwc/terms/Organism
- sample[organism-part]: 
   - http://purl.obolibrary.org/obo/UBERON_0000475
   - http://purl.obolibrary.org/obo/NCIT_C103199

**Comment by jsheunis** [comment]
Current working demo available: https://jsheunis.github.io/tabby-to-catalog-demo/#/dataset/9e2708d2-ae62-5f4e-9753-d2bf89d83029/0.1.0 (click on the SFB1451 tab)

<img width="1248" alt="Screenshot 2023-10-10 at 15 33 56" src="https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/10141237/6cc45dee-0564-4712-917d-a0c39c840bb5">


This uses additional dataset-level metadata in the following form:

```json
"additional_display_definitions": {
        "SFB1451": {
            "keys": {
                "homepage": "https://schema.org/mainEntityOfPage",
                "CRC project": "https://schema.org/ResearchProject",
                "data controller": {
                    "self": "https://w3id.org/dpv#hasDataController",
                    "email": "https://schema.org/email",
                    "name": "https://schema.org/name"
                },
                "sample (organism)": "http://purl.obolibrary.org/obo/UBERON_0000468",
                "sample (organism part)": "http://purl.obolibrary.org/obo/UBERON_0000475",
                "Used for": "http://www.w3.org/ns/prov#hadUsage"
            },
            "values": {
                "homepage": "https://schema.org/URL",
                "CRC project": "https://schema.org/Text",
                "data controller": {
                    "email": "https://schema.org/Text",
                    "name": "https://schema.org/Text"
                },
                "sample (organism)": [
                    "http://purl.obolibrary.org/obo/NCBITaxon_9238",
                    "http://purl.obolibrary.org/obo/NCBITaxon_30457",
                    "http://purl.obolibrary.org/obo/NCBITaxon_79643"
                ],
                "sample (organism part)": "http://purl.obolibrary.org/obo/UBERON_0013702",
                "Used for": "https://schema.org/Text"
            }
        }
    }
```

It's a custom hacky solution, but I think useful for making the SFB catalog richer. If we like this, I will commit the code to an SFB1451-specific branch in `datalad-catalog`

**Comment by mslw** [comment]
I think it looks great!

I don't have the brainpower to speak about the details today (e.g. whether the metadata form is optimal), but it looks pretty much like what I would imagine for this tab.

**Comment by jsheunis** [comment]
In order to apply this to the whole sfb1451-projects-catalog, there are several options:
1. **Regenerate metadata**: this will require updating the `load_tabby.py` script in `tabby-utils` to make it add the `additional_display_definitions` field to a dataset metadata record. This might also require rerunning the (full?) metadata extraction and catalog generation pipeline.
2. **Update metadata**: run through the existing catalog metadata and update the dataset-level metadata items of all datasets containing tabby records to also include a `additional_display_definitions` field.
3. **Add metadata on the fly in the browser**: the catalog metadata stay the same, and only the javascript changes by including a function that updates the metadata of a selected dataset to include the `additional_display_definitions` field. This is possible because all keys/values in the `additional_display_definitions` object can be predicted from the keys/values in the `additional_display` object with some assumptions and defaults. This function can likely be called when the user selects the `SFB1451` tab.

I'm leaning towards option 3 because that limits the custom/hacky changes to Javascript and leaves the metadata and metadata-generating scripts untouched. This also fits into the same approach that will be necessary to render the linked data in the `SFB1451` tab, as indicated by

> If we like this, I will commit the code to an SFB1451-specific branch in datalad-catalog

i.e. sfb1451-specific changes in a separate branch of `datalad-catalog`

@mslw keen to hear your thoughts on this.

**Comment by mslw** [comment]
(1) seems reasonable; given a specification I should be able to update tabby-loaders. All tabby metadata would have to be removed and re-added, but the other metadata could stay (dataset versions and IDs would be unaffected).

(2) is something I'd be the most hesitant about; whenever I can I prefer to process metadata before it goes into `catalog add`

(3) also seems good - especially given that it requires the least changes from me ;) If I understand correctly, this would currently use a pre-set "mapping" for table rows such as "homepage", "sample(organism)" etc?

**Comment by jsheunis** [comment]
> If I understand correctly, this would currently use a pre-set "mapping" for table rows such as "homepage", "sample(organism)" etc?

Indeed. Although we could define this mapping in a separate json file and then read it on demand, meaning that sucha. mapping could change over time without having to change code.

**Comment by jsheunis** [comment]
I've started figuring out what would be necessary to achieve option 3, and I now think it's not such great option anymore. Too many custom hacks in the catalog. Given that `tabby-utils` is already geared towards handling the SFB1451-specific tabby data, I think it makes more sense to update that code with more specifics. This means edits to that code and then going with option 1. I will make the amendments in the python code.
