### ISSUE TITLE
Some version labels are not useful

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#42]
https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/e4cef344-a6bd-5002-b7cd-550b0486be01/GITSHA%20408ae5bd16

![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/15a74021-43a3-4ac3-9114-c68d9f91170d)

I think the record simply need to be fixed, and say "latest".

**Comment by mslw** [comment]
This particular one comes from tabby where version was reported as `GITSHA 408ae5bd16`.

The catalog technically allows any string to be a version, but practically expects a git shasum. The html + JS truncates version at first 7 characters: https://github.com/datalad/datalad-catalog/blob/ae1724854fceac8e76fec5b1c520ac91e76387d3/datalad_catalog/catalog/templates/dataset-template.html#L15

I will update the tabby record in the dataset to drop the "GITSHA".
