### ISSUE TITLE
Not all urls should be https by default

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#43]
Z02 sub-datasets files were reported (in tabby files sent to me) with [UNC](https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention) paths in place of URL. AFAIK these were not altered by my metadata extraction. These paths / URLs start with `//uk-koeln.lolal/daten/...`. It looks like catalog code adds "https:" in front when displaying the download button.

(independent of that is the fact that the UNC paths reported in tabby were malformed to begin with - part of the path is duplicated)

**Comment by jsheunis** [comment]
This seems to be the browser doing its job with `href` property, and I don't have an immediate idea how to approach it differently. Will investigate.

**Comment by jsheunis** [comment]
This is how it works:
- the catalog displays a downloadable file if the file has an associated URL in the metadata
- the download link has the `href` property set to the URL
- if the url is a relative path, it will be relative to the specific domain.
- if the url is UNC, it's relative to the root which is http(s)

In any case, a UNC path is not really useful in the case of a catalog as far as I can tell. So a suggestion could be to display it as a normal file without a download link. THis means: if the url does not contain "http", don't make it downloadable.

Thoughts?

**Comment by mslw** [comment]
I think it makes sense, with a little reservation.

- That a link is not functional does not bother us - some URLs may require authentication, or physical network access, but remain very valuable even if most viewers can't access them outright.
- The catalog can not decide whether the link leads to a publicly available resource (and it should not decide).
- If a URL of any kind is presented as relative to catalog instance's domain, download will be doomed to fail (unless for a very specific deployment where data is actually located next to catalog), and in this case I agree that there's no value in showing a download link
- Requiring the URL to contain "http" would be too restrictive - although my browser does not handle e.g. (s)ftp, I can easily copy it or have a registered handler for those. How about requiring the URLs to contain a scheme?

**Comment by jsheunis** [comment]
> Requiring the URL to contain "http" would be too restrictive - although my browser does not handle e.g. (s)ftp, I can easily copy it or have a registered handler for those.

The url is still contained in the datalad dataset right, so still accessible via datalad. Or do you mean it would specifically be useful to be able to see and copy the URL, irrespective of whether a download via the catalog in a web browser would work?

> How about requiring the URLs to contain a scheme?

What exactly do you mean with this? As in https://en.wikipedia.org/wiki/List_of_URI_schemes?

**Comment by mslw** [comment]
> > Requiring the URL to contain "http" would be too restrictive - although my browser does not handle e.g. (s)ftp, I can easily copy it or have a registered handler for those.
> 
> The url is still contained in the datalad dataset right, so still accessible via datalad. Or do you mean it would specifically be useful to be able to see and copy the URL, irrespective of whether a download via the catalog in a web browser would work?

I mean the latter.

If I understood your analysis correctly, the only special case is this: "if the url is a relative path, it will be relative to the specific domain". There, the browser essentially misinterprets an intended URL (albeit an odd one) as a catalog-relative path. If an URL is an absolute one (https, sftp, ...) then it is reported as is, no misinterpretation.

> 
> > How about requiring the URLs to contain a scheme?
> 
> What exactly do you mean with this? As in https://en.wikipedia.org/wiki/List_of_URI_schemes?

Yes (this is returned e.g. as a component of `ParseResult` by Python's `urllib.parse.urlparse`). Sorry for brevity
