### ISSUE TITLE
Filter by author not working

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#44]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/0ef87896-e383-4ba1-a5ab-d6adcf7d344c)

Unlike the filtering by keyword, filtering by dataset or author name seems to have no effect.

Sorting by name or modification works, though.

**Comment by mslw** [comment]
Duplicate of #10

**Comment by mih** [comment]
OK, so an old issue. Thx. I think there is no point in keeping duplicates open.
