### ISSUE TITLE
Mention that (sub)dataset filtering is only for immediate subdatasets

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#45]
I think this is very useful functionality for the SFB superdataset, but becomes increasingly pointless towards leaf-datasets, or with dataset that have few subdatasets.

This may lead to the expectation that "filtering" is actually "searching", and result in frustration when there are no hits.

Personally, I find that the term "filtering" already communicate the scope clearly. But maybe we can tweak the UX a bit more. For example:

https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/ee671e31-3c6e-4d83-952a-cfc66c84390e/268104da80180112470f7fbd377d154dcb2cac4c

only has a single subdataset, and we offer "filtering". Maybe we should increase the threshold to `>3`?

**Comment by jsheunis** [comment]
Do you mean that the filtering options (image below) should only be displayed for `Nsubdatasets > 3`?

<img width="1224" alt="Screenshot 2023-09-27 at 13 09 03" src="https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/10141237/8666486f-8051-4f89-8f93-ea3bb2e02cde">

**Comment by mih** [comment]
Yes, but that is just a thought. It is already off for zero subdatasets -- which makes sense. But it is on for one subdataset -- where a filter can only achieve a complete or an empty list. Technically OK, but UX-wise poses the issue I tried to describe above.
