### ISSUE TITLE
Create an efficient way to create dataset file listing

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#47]
- we need a way to quickly create file lists (path & size) from datasets
  - also at the order of ca. 40 thousand files
  - without the need to get annexed content
- bypassing metalad and going straight to catalog schema may be preferred
  - ATM I am not sure whether the released version of `metalad_core` file extractor contains performance improvements introduced a while back
  - `catalog-translate` has been optimized for handling files with various metadata (repeated discovery of matching translator), not files with multiple

- if a script as written, it can be reused for DataLad datasets that cannot be shared in a way other than generating tabby records

**Comment by jsheunis** [comment]
Just noting a related development at https://github.com/psychoinformatics-de/datalad-tabby/pull/60, although my understanding is that the current issue wants to generate the file listing for datalad datasets or git repos, while the tabby script is doing that for any directory (and its subdirectory) with the specific aim of being independent of DataLad.

**Comment by mslw** [comment]
Delineation from related efforts:

- https://github.com/psychoinformatics-de/datalad-tabby/pull/60 as you say deals with directories
  - it uses `stat()` for file size, which would emit `FileNotFoundError` for absent annexed file ("broken link")
  - it uses `glob("*")` to list contents, which would include `.git` if used recursively
- next's [iter_dir](https://github.com/datalad/datalad-next/blob/main/datalad_next/iter_collections/directory.py)
  - recursive needs to be written on top
  - probably (?) has the same problem with annexed content
- next's [iter_gitworktree](https://github.com/datalad/datalad-next/blob/main/datalad_next/iter_collections/gitworktree.py)
  - probably the closest but does not check/report size

**Comment by mslw** [comment]
Another related effort is https://github.com/datalad/datalad-metalad/blob/dev_0.5/iter_test/iterate_dataset.py which is a significant performance improvement to the existing `metalad_core` file extractor, but it is unmerged (meaning it would require a development version of metalad).

**Comment by mslw** [comment]
Ok, looks like I reinvented the wheel and made it square, because datalad status can be called on a dataset to yield all the required information much faster. This is now addressed in 868c321
