### ISSUE TITLE
Update `inject_metadata.py` to use datalad-catalog utilities

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#52]
The script/module https://github.com/psychoinformatics-de/sfb1451-projects-catalog/blob/main/code/inject_metadata.py contains several functions to generate the base structure of a catalog-compliant metadata item. This functionality will be available in `datalad-catalog` pending the merging of https://github.com/datalad/datalad-catalog/pull/378. Once that is done, this module should be updated to use those new utility functions.

**Comment by jsheunis** [comment]
Rather, this script: https://github.com/sfb1451/tabby-utils/blob/main/load_tabby.py

Or is the former still used and useful to update? @mslw

**Comment by mslw** [comment]
We covered this in the lab meeting, but FTR: both are being used.
- tabby-utils repo covers processing of tabby files (adding records to datasets, extracting metadata straight into catalog)
- this repo covers all other curation / metadata processing
