### ISSUE TITLE
Rephrase empty content tab placeholder text

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#65]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/0a52026f-c4db-4d02-8224-9a8bbec0cfd9)

The text may not be factually correct. it well be that dataset content is available. The relevant aspect here is: the catalog record does not have content information.

And this is what I would post in that case.

> This catalog record contains no information on dataset content.

**Comment by jsheunis** [comment]
easy fix in the JS code, will do
