### ISSUE TITLE
Exclude self or draft catalog URL

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#66]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/6ea5632e-52c1-4f03-82b3-8ebb44ae4a1f)

The highlighted URL is undesirable IMHO.

1. It is practically `self`, ie. the page that I am viewing
2. It is outdated once the draft catalog is posted at data.sfb1451.de

So depending on the origin of this information, the URL should be removed, or be definitely removed. ;-)

I think it is fine if individual data controllers consider a particular dataset catalog page to be the main representation of a dataset.

In general, however I think it is too effortful to maintain references to `self` as part of a records that is invalidated by moving the catalog from A to B.

**Comment by mslw** [comment]
The dataset page you are viewing is generated from a tabby record. The highlighted Homepage URL was provided explicitly as part of the tabby record by its submitter.

I agree with your assessment (even more so, I think the URL points to an already outdated dataset version). But I am always undecided whether to hand-adjust submitted metadata or just report them as they come - in this case I only contacted the submitter (yesterday) with a suggestion that I remove the 2nd and 3rd URL.

But from what I see, this still falls under "should be removed"?
