### ISSUE TITLE
Subdataset pages do not open in new tab

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#72]
I tend to middle-click in links to open them in a new tab. This is not possible, and now context menu action allows opening navigation links (except for tabs and header links) in a new tab.

This forces a reader to leave the present catalog page for the majority of browsing needs.

**Comment by jsheunis** [comment]
I think this is a regression of some sort. This functionality was made available in https://github.com/datalad/datalad-catalog/issues/287

I will investigate.

**Comment by mih** [comment]
Given that this happens, I think we should be looking into tests for the web UI eventually.

**Comment by jsheunis** [comment]
Agreed. Some minor suggestions for linting javascript/html made here: https://github.com/datalad/datalad-catalog/issues/107.

Created a dedicated issue for web ui testing here: https://github.com/datalad/datalad-catalog/issues/399

**Comment by mslw** [comment]
Ctrl-click works for me on Firefox, but it's more of a workaround - middle-click does not work for me either.

**Comment by jsheunis** [comment]
It could be a browser / os thing also, I will have a look.

**Comment by mslw** [comment]
Middle- or right-click works now. I believe this is due to the changes introduced with #83 ("Adds an href property to all subdataset links on all dataset pages").
