### ISSUE TITLE
Future-proof Z03 subdataset organization

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#73]
Both MR dataset reflect the acquisitions down at each contributing site. So they are practically the same dataset. Even if they are no yet aligned, and there is no immediate superdataset for them, it would make sense to communicate that via their names and descriptions.

**Comment by mslw** [comment]
Per e-mail from today:

> we would be in favor of renaming the folders from "MRI_data" to "MRI_data_Juelich" and from "Z03-MRI-BIDS" to "MRI_data_Cologne".
