### ISSUE TITLE
URL needs to be an array for the "view on..." button to show

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#88]
I noticed that the catalog schema for dataset has:

https://github.com/psychoinformatics-de/sfb1451-projects-catalog/blob/827d7365d0456c61938ef44614231eb0bb6845ac/docs/schema/jsonschema_dataset.json#L44-L50

but the JS code used in the template to decide whether to show the "view on GitHub / GIN" only triggers when the URL is an array:

https://github.com/psychoinformatics-de/sfb1451-projects-catalog/blob/827d7365d0456c61938ef44614231eb0bb6845ac/docs/assets/app_component_dataset.js#L136-L155

I only had a cursory look at the datalad-catalog repo, but it seems that this is also the case upstream. I cannot currently investigate further, but making the note for the future.

note: This was discovered when trying to re-use "homepage" from tabby metadata as a potential URL. Decided to always return an array, if a matching URL is found.

**Comment by jsheunis** [comment]
Good catch. I think this is an unintended discrepancy. Good to have this issue open. I will link a new one in `datalad-catalog` as well.
