### ISSUE TITLE
Introduce alias- and ID-based url navigation

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#93]
Most of the necessary work has been done in https://github.com/datalad/datalad-catalog/pull/430

Once that PR is considered complete, the relevant changes can be applied to this catalog instance.

**Comment by mslw** [comment]
Note: the alias- and ID-based URL navigation *capability* is now present, thanks to updating the catalog code. No aliases or IDs are defined so far.

To define an alias or ID, "redirect" files need to be placed. This will be done as demand arises.
