### ISSUE TITLE
Apply provenance-related features from upstream

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#94]
The latest updates to provenance metadata extraction and rendering in a catalog are contained in https://github.com/datalad/datalad-catalog/pull/433.

We should ensure that previously existing features and the latest changes are available to this catalog instance, so that provenance info can be rendered.

**Comment by jsheunis** [comment]
Latest update:
- datalad-catalog main already had the ability to understand runprov records (based on it being incorporated into the catalog schema) and render them, for a long time
- The runprov extractor from metalad was updated and incorporated into `datalad-catalog` as a standalone script in https://github.com/datalad/datalad-catalog/pull/433. This PR also added a script to `datalad-catalog/tools` demonstrate how the extractor can be used.
- The run-record rendering was tweaked in https://github.com/datalad/datalad-catalog/pull/460

A demo for how this works for the [clustered-network-pub dataset](https://github.com/psychoinformatics-de/ClusteredNetwork_pub):

1. Clone the dataset: `git clone https://github.com/psychoinformatics-de/ClusteredNetwork_pub.git`
2. Create a new empty catalog: `datalad catalog-create --catalog clustercat`
3. Run the tool script: `python datalad-catalog/tools/extract_core_runprov.py ClusteredNetwork_pub clustercat`
   This script:
   - takes paths to the DataLad dataset and the empty catalog as arguments
   - extracts core metadata as well as runprov metadata from the dataset, using the relevant extractor modules in `datalad-catalog/extractors`
   - translates these records to catalog-ready records
   - adds the records to the catalog
4. Set the catalog home page
   ```
   datalad catalog-set --catalog clustercat --dataset-id bfe12f51-3f30-4ceb-b4de-9b6f85f2ef6c --dataset-version 62e2fe8326350e27a381fa4b28afc4f83fa6b893 home
   ```
5. serve the catalog: `datalad catalog-serve -c clustercat`

video:

https://github.com/sfb1451/metadata-catalog/assets/10141237/77f115d1-4ed9-4e71-9f2a-9e3fa6302bdd

**Comment by mih** [comment]
This has been resolved. Discussed in lab meeting 2024-06-06
